services:
  db:
    image: postgres:15 # Or latest stable version
    restart: always
    environment:
      POSTGRES_DB: mydatabase # Choose your DB name
      POSTGRES_USER: myuser     # Choose your username
      POSTGRES_PASSWORD: mypassword # Choose a strong password!
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: